// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/search.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { content: [{ type: "text", text: "Ikke autentisert. Logg inn i Snakk CRM f\xF8rst." }], isError: true };
  }
  return null;
}

// src/lib/mcp/tools/search.ts
var search_default = defineTool({
  name: "search",
  title: "S\xF8k i CRM",
  description: "S\xF8k p\xE5 tvers av leads, salgsmuligheter, selskaper og kontakter. Returnerer maks 10 treff per entitetstype.",
  inputSchema: {
    query: z.string().min(2).describe("S\xF8ketekst (min. 2 tegn) \u2013 firmanavn, kontaktperson eller e-post."),
    type: z.enum(["lead", "salgsmulighet", "selskap", "kontakt"]).optional().describe("Begrens til \xE9n entitetstype. Utelat for \xE5 s\xF8ke alt.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, type }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const q = `%${query}%`;
    const wanted = (t) => !type || type === t;
    const results = [];
    if (wanted("lead")) {
      const { data } = await sb.from("leads").select("id, firmanavn, kontaktperson, status, ansvarlig, e_post, sist_aktivitet").or(`firmanavn.ilike.${q},kontaktperson.ilike.${q},e_post.ilike.${q}`).limit(10);
      for (const r of data || []) results.push({ type: "lead", ...r });
    }
    if (wanted("salgsmulighet")) {
      const { data } = await sb.from("salgsmuligheter").select("id, navn, status, forventet_mrr, ansvarlig, kontaktperson, e_post, sist_aktivitet").or(`navn.ilike.${q},kontaktperson.ilike.${q},e_post.ilike.${q}`).limit(10);
      for (const r of data || []) results.push({ type: "salgsmulighet", ...r });
    }
    if (wanted("selskap")) {
      const { data } = await sb.from("selskaper").select("id, firmanavn, kundestatus, mrr, kundeansvarlig, sist_aktivitet").or(`firmanavn.ilike.${q},domene.ilike.${q}`).limit(10);
      for (const r of data || []) results.push({ type: "selskap", ...r });
    }
    if (wanted("kontakt")) {
      const { data } = await sb.from("kontakter").select("id, navn, rolle, e_post, telefon, selskap_id").or(`navn.ilike.${q},e_post.ilike.${q}`).limit(10);
      for (const r of data || []) results.push({ type: "kontakt", ...r });
    }
    return {
      content: [{ type: "text", text: JSON.stringify({ count: results.length, results }, null, 2) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/pipeline-summary.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
var pipeline_summary_default = defineTool2({
  name: "pipeline_summary",
  title: "Pipeline-sammendrag",
  description: "Aggregert oversikt over aktiv MRR, pipeline-verdi, vektet pipeline, vunnet/tapt denne m\xE5neden, og fordeling per fase.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const now = /* @__PURE__ */ new Date();
    const firstOfMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`;
    const { data: deals } = await sb.from("salgsmuligheter").select("status, forventet_mrr, sannsynlighet, vunnet_dato, tapt_dato");
    const { data: companies } = await sb.from("selskaper").select("mrr, kundestatus");
    const open = (deals || []).filter((d) => !["Vunnet", "Tapt"].includes(d.status));
    const byStage = {};
    for (const d of open) {
      const s = d.status || "Ukjent";
      if (!byStage[s]) byStage[s] = { count: 0, mrr: 0 };
      byStage[s].count++;
      byStage[s].mrr += d.forventet_mrr || 0;
    }
    const totalPipelineMrr = open.reduce((s, d) => s + (d.forventet_mrr || 0), 0);
    const weighted = open.reduce(
      (s, d) => s + (d.forventet_mrr || 0) * (d.sannsynlighet || 50) / 100,
      0
    );
    const wonMonth = (deals || []).filter((d) => d.vunnet_dato && d.vunnet_dato >= firstOfMonth);
    const lostMonth = (deals || []).filter((d) => d.tapt_dato && d.tapt_dato >= firstOfMonth);
    const liveMrr = (companies || []).filter((c) => c.kundestatus === "Live").reduce((s, c) => s + (c.mrr || 0), 0);
    const pilotMrr = (companies || []).filter((c) => c.kundestatus === "Pilot").reduce((s, c) => s + (c.mrr || 0), 0);
    const summary = {
      aktiv_mrr: liveMrr + pilotMrr,
      live_mrr: liveMrr,
      pilot_mrr: pilotMrr,
      pipeline_mrr: totalPipelineMrr,
      vektet_pipeline_mrr: Math.round(weighted),
      aapne_salgsmuligheter: open.length,
      vunnet_denne_maaned: {
        antall: wonMonth.length,
        mrr: wonMonth.reduce((s, d) => s + (d.forventet_mrr || 0), 0)
      },
      tapt_denne_maaned: {
        antall: lostMonth.length,
        mrr: lostMonth.reduce((s, d) => s + (d.forventet_mrr || 0), 0)
      },
      per_fase: byStage
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/my-tasks.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
var my_tasks_default = defineTool3({
  name: "my_tasks",
  title: "Mine oppgaver",
  description: "Hent \xE5pne oppgaver for den innloggede brukeren (eller inkluder ferdige).",
  inputSchema: {
    include_completed: z2.boolean().optional().describe("Ta med oppgaver med status 'Ferdig'. Default false."),
    limit: z2.number().int().min(1).max(200).optional().describe("Maks antall oppgaver. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_completed, limit }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    let q = sb.from("oppgaver").select("id, oppgave, frist, prioritet, status, ansvarlig, lead_id, salgsmulighet_id, selskap_id").eq("user_id", userId).order("frist", { ascending: true }).limit(limit ?? 50);
    if (!include_completed) q = q.neq("status", "Ferdig");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ count: data?.length ?? 0, tasks: data ?? [] }, null, 2) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/overdue-followups.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
var overdue_followups_default = defineTool4({
  name: "overdue_followups",
  title: "Utg\xE5tt oppf\xF8lging",
  description: "Leads (>48t uten aktivitet) og salgsmuligheter (>72t uten aktivitet) som trenger oppf\xF8lging.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const now = Date.now();
    const lead48 = new Date(now - 48 * 3600 * 1e3).toISOString().split("T")[0];
    const sm72 = new Date(now - 72 * 3600 * 1e3).toISOString().split("T")[0];
    const { data: leads } = await sb.from("leads").select("id, firmanavn, kontaktperson, status, ansvarlig, sist_aktivitet").not("status", "in", '("Ikke aktuelt","Konvertert til salg","Konvertert til partner")').lt("sist_aktivitet", lead48).order("sist_aktivitet", { ascending: true }).limit(50);
    const { data: sm } = await sb.from("salgsmuligheter").select("id, navn, status, ansvarlig, forventet_mrr, sist_aktivitet").not("status", "in", '("Vunnet","Tapt")').lt("sist_aktivitet", sm72).order("sist_aktivitet", { ascending: true }).limit(50);
    const payload = {
      leads_stale: leads || [],
      salgsmuligheter_stale: sm || [],
      thresholds: { lead_hours: 48, salgsmulighet_hours: 72 }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-salgsmulighet.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
var get_salgsmulighet_default = defineTool5({
  name: "get_salgsmulighet",
  title: "Hent salgsmulighet",
  description: "Full info om en salgsmulighet inkludert de 10 siste aktivitetene.",
  inputSchema: { id: z3.string().uuid().describe("ID p\xE5 salgsmuligheten.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const { data: sm, error } = await sb.from("salgsmuligheter").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!sm) return { content: [{ type: "text", text: "Ikke funnet" }], isError: true };
    const { data: acts } = await sb.from("aktiviteter").select("id, type, dato, tittel, beskrivelse, aktivitet_kilde").eq("salgsmulighet_id", id).order("dato", { ascending: false }).limit(10);
    const payload = { ...sm, siste_aktiviteter: acts || [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-selskap.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^4.4.3";
var get_selskap_default = defineTool6({
  name: "get_selskap",
  title: "Hent selskap",
  description: "Selskap med tilh\xF8rende kontakter og salgsmuligheter.",
  inputSchema: { id: z4.string().uuid().describe("Selskaps-ID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const { data: s, error } = await sb.from("selskaper").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!s) return { content: [{ type: "text", text: "Ikke funnet" }], isError: true };
    const { data: kontakter } = await sb.from("kontakter").select("id, navn, rolle, e_post, telefon").eq("selskap_id", id);
    const { data: sm } = await sb.from("salgsmuligheter").select("id, navn, status, forventet_mrr").eq("selskap_id", id);
    const payload = { ...s, kontakter: kontakter || [], salgsmuligheter: sm || [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^4.4.3";
var create_task_default = defineTool7({
  name: "create_task",
  title: "Opprett oppgave",
  description: "Opprett en ny oppgave for den innloggede brukeren.",
  inputSchema: {
    oppgave: z5.string().min(1).describe("Oppgavetittel."),
    frist: z5.string().optional().describe("Frist (ISO-dato eller ISO-timestamp)."),
    prioritet: z5.enum(["Lav", "Medium", "H\xF8y"]).optional().describe("Prioritet, default 'Medium'."),
    notater: z5.string().optional().describe("Fritekst-notater."),
    lead_id: z5.string().uuid().optional(),
    salgsmulighet_id: z5.string().uuid().optional(),
    selskap_id: z5.string().uuid().optional(),
    kontakt_id: z5.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const email = ctx.getUserEmail() ?? "";
    const { data: profile } = await sb.from("profiles").select("display_name").eq("user_id", ctx.getUserId()).maybeSingle();
    const row = {
      oppgave: input.oppgave,
      frist: input.frist || null,
      prioritet: input.prioritet || "Medium",
      status: "\xC5pen",
      ansvarlig: profile?.display_name || email,
      notater: input.notater || "",
      lead_id: input.lead_id || null,
      salgsmulighet_id: input.salgsmulighet_id || null,
      selskap_id: input.selskap_id || null,
      kontakt_id: input.kontakt_id || null,
      user_id: ctx.getUserId()
    };
    const { data, error } = await sb.from("oppgaver").insert(row).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Oppgave opprettet: ${data.id}` }],
      structuredContent: { oppgave: data }
    };
  }
});

// src/lib/mcp/tools/create-activity.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z6 } from "npm:zod@^4.4.3";
var create_activity_default = defineTool8({
  name: "create_activity",
  title: "Logg aktivitet",
  description: "Logg en aktivitet/notat p\xE5 en lead, salgsmulighet, selskap eller kontakt.",
  inputSchema: {
    type: z6.enum(["Notat", "M\xF8te", "Samtale", "E-post", "Annet"]).describe("Aktivitetstype."),
    beskrivelse: z6.string().min(1).describe("Beskrivelse / notat."),
    tittel: z6.string().optional(),
    dato: z6.string().optional().describe("ISO-timestamp. Default n\xE5."),
    lead_id: z6.string().uuid().optional(),
    salgsmulighet_id: z6.string().uuid().optional(),
    selskap_id: z6.string().uuid().optional(),
    kontakt_id: z6.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const row = {
      type: input.type,
      tittel: input.tittel || "",
      beskrivelse: input.beskrivelse,
      dato: input.dato || (/* @__PURE__ */ new Date()).toISOString(),
      lead_id: input.lead_id || null,
      salgsmulighet_id: input.salgsmulighet_id || null,
      selskap_id: input.selskap_id || null,
      kontakt_id: input.kontakt_id || null,
      user_id: ctx.getUserId(),
      aktivitet_kilde: "mcp"
    };
    const { data, error } = await sb.from("aktiviteter").insert(row).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Aktivitet loggf\xF8rt: ${data.id}` }],
      structuredContent: { aktivitet: data }
    };
  }
});

// src/lib/mcp/tools/complete-task.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z7 } from "npm:zod@^4.4.3";
var complete_task_default = defineTool9({
  name: "complete_task",
  title: "Fullf\xF8r oppgave",
  description: "Marker en oppgave som ferdig.",
  inputSchema: { id: z7.string().uuid().describe("Oppgave-ID.") },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("oppgaver").update({ status: "Ferdig" }).eq("id", id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Oppgave ${id} markert som ferdig.` }],
      structuredContent: { oppgave: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tchmujgzcklwgptocbno";
var mcp_default = defineMcp({
  name: "snakk-crm-mcp",
  title: "Snakk CRM",
  version: "0.1.0",
  instructions: "Verkt\xF8y for Snakk CRM. Bruk `search` for \xE5 finne leads, salgsmuligheter, selskaper eller kontakter. Bruk `pipeline_summary` for aktiv MRR og pipeline-status, `my_tasks` og `overdue_followups` for prioritert arbeid, `get_salgsmulighet`/`get_selskap` for detaljer, og `create_task`/`create_activity`/`complete_task` for \xE5 oppdatere CRM. Alle handlinger kj\xF8res som den innloggede Snakk CRM-brukeren og respekterer RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_default,
    pipeline_summary_default,
    my_tasks_default,
    overdue_followups_default,
    get_salgsmulighet_default,
    get_selskap_default,
    create_task_default,
    create_activity_default,
    complete_task_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
